.TH SWIFTENV\-INSTALL 1

.SH NAME
swiftenv-install \- Install a version of Swift

.SH SYNOPSIS
swiftenv install [\-\-verbose] [\-\-list] [\-\-list-snapshots] [\-\-[no\-]build] [--no-clean] <version>

.SH DESCRIPTION

Installs a version of Swift.

.SH OPTIONS

\-\-verbose

.RS
Shows additional debugging information.
.RE

\-\-list

.RS
Lists all the Swift releases that can be installed.
.RE

\-\-list-snapshots

.RS
Lists all the Swift snapshot releases that can be installed.
.RE

\-\-build

.RS
Forces installation only from source.
.RE

\-\-no\-build

.RS
Forces installation only from binary releases of Swift.
.RE

\-\-no\-clean

.RS
Leaves the build directory intact for inspection and debugging.
.RE
