#!/usr/bin/env bash

set -e

if [ -z "$SWIFTENV_ROOT" ]; then
  SWIFTENV_ROOT=$HOME/.swiftenv
fi
export SWIFTENV_ROOT

find_libexec_path() {
  cd "$(dirname "${BASH_SOURCE[0]}")"
  cd "$(dirname "$(readlink "${BASH_SOURCE[0]}")")"
  echo "$PWD/../libexec"
}
export PATH="$(find_libexec_path):$PATH"

command="$1"
case "$command" in
"" )
  echo "Usage: swiftenv <command>"
  exit 1
  ;;
-v | --version )
  exec swiftenv---version
  ;;
* )
  command_path="$(command -v "swiftenv-$command" || true)"
  if ! [ -n "$command_path" ]; then
    echo "no such command \`$command'"
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac
