#!/usr/bin/env bash

set -e

VERSION=$1
if [ -z "$VERSION" ] ; then
  VERSION="$(swiftenv-version-name --dont-check)"
  if [ "$VERSION" == "system" ]; then
    echo "Usage: swiftenv install <version>"
    exit 1
  fi
fi

if [ -z "$TMPDIR" ] ; then
  export TMPDIR=/tmp
fi

PREFIX="$(swiftenv-prefix "$VERSION" || true)"
if [ -d "$PREFIX" ]; then
  echo "$VERSION is already installed."
  exit 1
fi

unsupported_binary_platform() {
  echo "Apple does not provide binary releases for $1."
  echo
  echo "You may manually install Swift and place it into:"
  echo "  $SWIFTENV_ROOT/versions/$VERSION"
  echo
  echo "Alternatively, you can force using a Ubuntu binaries by using the following:"
  echo "  $ env UBUNTU_VERSION=ubuntu15.10 swiftenv install $VERSION"
  echo
  exit 1
}

check_url() {
  status_code=$(curl -o /dev/null --silent --head --write-out '%{http_code}' "$1")
  if [ "$status_code" = "404" ]; then
    echo "$VERSION was not found on swift.org."
    echo "  $1"
    exit 1
  elif [ "$status_code" != "200" ]; then
    echo "There was a network problem retreiving $VERSION, server returned $status_code."
    echo "  $1"
    exit 1
  fi
}

install_ubuntu_binary() {
  if [ -z "$UBUNTU_VERSION" ]; then
    if command -v "lsb_release" >/dev/null 2>&1; then
      if [ $(lsb_release -is) = "Ubuntu" ]; then
        UBUNTU_VERSION="ubuntu$(lsb_release -rs)"
        if [ "$UBUNTU_VERSION" != "ubuntu15.10" ] && [ "$UBUNTU_VERSION" != "ubuntu14.04" ]; then
          unsupported_binary_platform $UBUNTU_VERSION
        fi
      else
        unsupported_binary_platform "$(lsb_release -ds)"
      fi
    else
      unsupported_binary_platform "your distribution"
    fi
  fi

  URL="https://swift.org/builds/${UBUNTU_VERSION//./}/$VERSION/$VERSION-$UBUNTU_VERSION.tar.gz"
  check_url "$URL"

  mkdir -p "$TMPDIR/swiftenv-$VERSION"

  echo "Downloading $VERSION from $URL"
  curl "$URL" -s | tar xz -C "$TMPDIR/swiftenv-$VERSION"

  DESTINATION="$SWIFTENV_ROOT/versions/$VERSION"
  mv "$TMPDIR/swiftenv-$VERSION/$VERSION-$UBUNTU_VERSION" "$DESTINATION"
}

install_osx_binary() {
  URL="https://swift.org/builds/xcode/$VERSION/$VERSION-osx.pkg"
  check_url "$URL"

  echo "Downloading $VERSION from $URL"
  curl -sLo "$TMPDIR/swiftenv-$VERSION.pkg" "$URL"
  sudo installer -pkg "$TMPDIR/swiftenv-$VERSION.pkg" -target /
}

mkdir -p "$SWIFTENV_ROOT/versions"
case $(uname) in
'Linux' )
  install_ubuntu_binary
  ;;
'Darwin' )
  install_osx_binary
  ;;
* )
  echo "There are no binary releases of Swift for $(uname). Please manually install Swift into $SWIFTENV_ROOT/versions/$VERSION"
  exit 1
  ;;
esac

swiftenv-rehash
swiftenv-global "$VERSION"
