#!/usr/bin/env bash

set -e

version_exists() {
  local version="$1"
  local path="$SWIFTENV_ROOT/versions/$version"
  [ -d "$path" ]
}

if [ -z "$SWIFT_VERSION" ]; then
  SWIFT_VERSION_FILE=$(swiftenv-version-file)
  if [ "$SWIFT_VERSION_FILE" == "$SWIFTENV_ROOT/version" ] && ! [[ -f "$SWIFT_VERSION_FILE" ]]; then
    echo "system"
    exit
  fi

  SWIFT_VERSION=$(cat "$SWIFT_VERSION_FILE")
fi

if version_exists "$SWIFT_VERSION" || [ "$SWIFT_VERSION" == "system" ]; then
  echo $SWIFT_VERSION
else
  echo "swiftenv: version \`$SWIFT_VERSION' is not installed"
  exit 1
fi
