#!/usr/bin/env bash
# Uninstalls a Swift version
# completes

set -e

if [ "$1" = "--complete" ]; then
  exec swiftenv-versions --bare
fi

VERSION=$1
if [ -z "$VERSION" ] ; then
  echo "Usage: swiftenv uninstall <version>"
  exit 1
fi

if [ "$VERSION" == "system" ]; then
  echo "$VERSION is uninstallable."
  exit 1
fi

if [ -d "$SWIFTENV_ROOT/versions/$VERSION" ]; then
  VERSION_DIRECTORY="$SWIFTENV_ROOT/versions/$VERSION"
elif [ -d "$SWIFTENV_ROOT/versions/swift-$VERSION" ]; then
  VERSION_DIRECTORY="$SWIFTENV_ROOT/versions/swift-$VERSION"
elif [ -d "/Library/Developer/Toolchains/swift-$VERSION.xctoolchain" ]; then
  VERSION_DIRECTORY="/Library/Developer/Toolchains/swift-$VERSION.xctoolchain"
else
  echo "$VERSION is not installed."
  exit 1
fi

CURRENT_VERSION=$(cat "$SWIFTENV_ROOT/version")
if [ "$VERSION" == "$CURRENT_VERSION" ]; then
  rm -f "$SWIFTENV_ROOT/version"
fi

if [[ "$VERSION_DIRECTORY" == "/Library/Developer/Toolchains/"* ]]; then
  if [ "$(readlink /Library/Developer/Toolchains/swift-latest.xctoolchain)" == "$VERSION_DIRECTORY" ]; then
    sudo rm -fr /Library/Developer/Toolchains/swift-latest.xctoolchain
  fi

  sudo rm -fr "$VERSION_DIRECTORY"
else
  rm -fr "$VERSION_DIRECTORY"
fi

swiftenv rehash
