#!/usr/bin/env bash
# Rehash pyenv shims

set -e

SHIM_PATH=$SWIFTENV_ROOT/shims

mkdir -p "$SHIM_PATH"

# List all basenames of executables for every installed Swift version
list_executable_names() {
  VERSIONS_DIR="$SWIFTENV_ROOT/versions/$version"

  for path in "$VERSIONS_DIR"/*; do
    if [ -d "$path" ]; then
      for file in "$path/usr/bin/"*; do
        echo "${file##*/}"
      done
    fi
  done

  if [ -d "/Library/Developer/Toolchains" ]; then
    VERSIONS_DIR="/Library/Developer/Toolchains"

    for path in "$VERSIONS_DIR"/*.xctoolchain; do
      if [ -d "$path" ]; then
        for file in "$path/usr/bin/"*; do
          echo "${file##*/}"
        done
      fi
    done
  fi
}

remove_stale_shims() {
  local shim
  for shim in "$SHIM_PATH"/*; do
    if [[ "$registered_shims" != *" ${shim##*/} "* ]]; then
      rm -f "$shim"
    fi
  done
}

create_shims() {
  local shim
  for shim in $registered_shims; do
    create_shim "$shim"
  done
}

create_shim() {
  cat > "$SHIM_PATH/$1" <<SH
#!/usr/bin/env bash
set -e
exec "$(command -v swiftenv)" exec "$1" "\$@"
SH
  chmod +x "$SHIM_PATH/$1"
}

registered_shims=" $(list_executable_names | sort -u) "
remove_stale_shims
create_shims
