#!/usr/bin/env bash

set -e

COMMAND=$1

if [ -z "$COMMAND" ] ; then
  echo "Usage: swiftenv which <command>"
  exit 1
fi

if [ "$(swiftenv-version-name)" == "system" ]; then
  env PATH=/usr/bin:/bin which $COMMAND
  exit
else
  COMMAND_PATH="$(swiftenv-prefix)/usr/bin"
fi

if [ -x "$COMMAND_PATH/$COMMAND" ]; then
  echo "$COMMAND_PATH/$COMMAND"
else
  exit 127
fi
