#!/usr/bin/env bash
# Summary: Show the current selected Swift version and how it was selected.

set -e

VERSION="$(swiftenv-version-name)"
ORIGIN="$(swiftenv-version-origin)"

echo "$VERSION (set by $ORIGIN)"
