#!/usr/bin/env bash
# Set or show the local Swift version

set -e

VERSION=$1
VERSION_FILE=".swift-version"

version_exists() {
  local version="$1"
  local path="$SWIFTENV_ROOT/versions/$version"
  [ -d "$path" ]
}

if [ "$VERSION" = "--unset" ]; then
  rm -f $VERSION_FILE
elif [ -z "$VERSION" ]; then
  if [ -f "$VERSION_FILE" ]; then
    cat "$VERSION_FILE"
  else
    echo "swiftenv: version is not set"
    exit 1
  fi
elif version_exists "$VERSION"; then
  echo "$VERSION" > "$VERSION_FILE"
else
  echo "swiftenv: version \`$VERSION' is not installed"
fi
