#!/usr/bin/env bash
# Summary: List all available commands

set -e

IFS=: paths=($PATH)

shopt -s nullglob

{ for path in "${paths[@]}"; do
    for command in "$path/swiftenv-"*; do
      command="${command##*swiftenv-}"
      echo $command
    done
  done
} | sort -u
